### ISSUE TITLE
question about website performance

### ISSUE THREAD

**Issue by sideshowtom** [jeff-zucker/solid-ui-components#14]
Its pretty awesome, but a question which is I guess about performance:
I go to https://jeff-zucker.solidcommunity.net/sp4/
and go to "People & Teams" and I get only the first few.

I ask because if I ever get it together I want to use these components.

Maybe when I do I can use it to make a site to read/write/modify/use LinkML yaml files, but nooo promises

**Comment by jeff-zucker** [comment]
Thanks, it's in development and I have not touched on performance yet, waiting till I am further along with the code.  I haven't had it only give the first few except when there are network problems.  I tried now and there was no problem.  The final code should be a lot leaner, won't import from CDNs, have the possibility to omit comunica, and other things that should improve performance.  In terms of using it as a basis for the Solid Project dot org website, I am thinking more of using it to generate static pages rather than serving live, though if performance improves enough, we might consider that.

**Comment by sideshowtom** [comment]
OT I know, but LinkML is pretty awesome too, and if it could be brought into the solid world it would bring a lot of advantages.  LinkML schemas abstract a lot of things including RDF, Json-LD, Sparql, even spreadsheets. They are planning to implement a diff of LinkML schemas which would be very useful.  Also LinkML schemas can inherit from each other so that means Sparql queries could have an inheritance ancestry, which could be very useful if what RV says is true that every app will be a query.

But for me just beginning all over again with reading and writing files is the level I'm at.

**Comment by jeff-zucker** [comment]
LinkML is high on the list of things I know I should know something abut but don't know anything about.

**Comment by jeff-zucker** [comment]
So you're thinking that someone could create a YAML site or component description and soid-ui-components could auto-convert that to RDF and display the site or component?  That would be quite cool.

**Comment by jeff-zucker** [comment]
Actually, because of the way I've written things, I'm not even sure the conversion is necessary.  It could work as YAML -> JSON -> solid-ui-components.  Because I translate RDF into JSON along the line anyway.

**Comment by sideshowtom** [comment]
I was just thinking of a general converter from linkml, which is in yaml, to rdf and the other way too.  Also the other conversions linkml-convert can do.  Just basically a front end for linkml-convert, and the resulting resources would go in your pod.

But maybe if the linkml would convert to rdf that describes solid-ui-components, yes, that could be displayed too.  That might be step 2, to have some logic to detect solid-ui-components.

**Comment by jeff-zucker** [comment]
Oh, I see, I didn't realize linkml was itself yaml, yes that sounds like a great project.  Go for it and let me know if you want to bounce ideas or whatever.  Meanwhile I may pursue the other direction - let people create in yaml rather than rdf - that would help de-mystify things for people new to RDF.

**Comment by sideshowtom** [comment]
Yeah I think that's part of the idea of LinkML, to integrate the non-RDF with RDF.  You might want to make your yaml files LinkML files so its compatible.  You see, if I just type long enough I end up telling people what to do :)

Anyway, I hope to try this linkml-convert with solid-ui-components front end idea.  The hard part I think will be that Brython thing.  For the solid-ui-components, I think you've made it pretty easy :)

**Comment by jeff-zucker** [comment]
Sigh, I'm glad you're telling me what to do.  I think you may have pushed me over the edge to the point where I need to  RTFM on LinkML.  Darn it, another thing to be interested in! :-)

**Comment by jeff-zucker** [comment]
AFAIK, this is a solidcommunity.net issue with speed.  I should keep it in mind though and have minified versions of all libraries.
